### ISSUE TITLE
how to start the program and save the image?

### ISSUE THREAD

**Issue by yuzouDE** [WolfCarver/BaslerDemoSoftwareTrigger#1]

**Comment by yuzouDE** [comment]
I changed the SN number to my camera. When I run in Mono, I got:

`* Assertion: should not be reached at metadata.c:2998


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
41163000-41173000 rwxp 00000000 00:00 0 
41626000-41686000 rwxp 00000000 00:00 0 
556d199b0000-556d19e3a000 r-xp 00000000 08:01 264713                     /usr/bin/mono-sgen
556d1a039000-556d1a041000 r--p 00489000 08:01 264713                     /usr/bin/mono-sgen
556d1a041000-556d1a047000 rw-p 00491000 08:01 264713                     /usr/bin/mono-sgen
556d1a047000-556d1a063000 rw-p 00000000 00:00 0 
556d1b372000-556d1b90c000 rw-p 00000000 00:00 0                          [heap]
7f11ff713000-7f11ff81d000 r--p 00000000 08:01 263194                     /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
7f11ff81d000-7f11ff827000 r-xp 00000000 08:01 525154                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7f11ff827000-7f11ffa26000 ---p 0000a000 08:01 525154                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7f11ffa26000-7f11ffa27000 r--p 00009000 08:01 525154                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7f11ffa27000-7f11ffa28000 rw-p 0000a000 08:01 525154                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7f11ffa28000-7f11ffa62000 r-xp 00000000 08:01 525153                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
7f11ffa62000-7f11ffc62000 ---p 0003a000 08:01 525153                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
7f11ffc62000-7f11ffc63000 r--p 0003a000 08:01 525153                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
7f11ffc63000-7f11ffc64000 rw-p 0003b000 08:01 525153                     /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libmurrine.so
7f11ffc64000-7f11ffc6a000 r-xp 00000000 08:01 2228411                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f11ffc6a000-7f11ffe69000 ---p 00006000 08:01 2228411                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f11ffe69000-7f11ffe6a000 r--p 00005000 08:01 2228411                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f11ffe6a000-7f11ffe6b000 rw-p 00006000 08:01 2228411                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f11ffe6b000-7f11ffeb2000 r-xp 00000000 08:01 2233066                    /lib/x86_64-linux-gnu/libblkid.so.1.1.0
7f11ffeb2000-7f12000b2000 ---p 00047000 08:01 2233066                    /lib/x86_64-linux-gnu/libblkid.so.1.1.0
7f12000b2000-7f12000b6000 r--p 00047000 08:01 2233066                    /lib/x86_64-linux-gnu/libblkid.so.1.1.0
7f12000b6000-7f12000b7000 rw-p 0004b000 08:01 2233066                    /lib/x86_64-linux-gnu/libblkid.so.1.1.0
7f12000b7000-7f12000b8000 rw-p 00000000 00:00 0 

=================================================================
	Native stacktrace:
=================================================================
	0x556d19a81eb5 - mono : (null)
	0x556d19a82251 - mono : (null)
	0x556d19a2e0c1 - mono : (null)
	0x556d19a814d2 - mono : (null)
	0x7f1210c04890 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x7f120ff00e97 - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7f120ff02801 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x556d19cf0d17 - mono : (null)
	0x556d19cd6313 - mono : (null)
	0x556d19cf0c98 - mono : (null)
	0x556d19cf1193 - mono : monoeg_assertion_message
	0x556d19bd16de - mono : (null)
	0x556d19bd6a29 - mono : (null)
	0x556d19b73f68 - mono : (null)
	0x556d19bfb7d6 - mono : (null)
	0x556d19ab8ace - mono : (null)
	0x556d19a86a33 - mono : (null)
	0x556d19a88d52 - mono : (null)
	0x556d199f04a5 - mono : (null)
	0x556d19a31756 - mono : (null)
	0x556d19a322d3 - mono : (null)
	0x41163393 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7f120ca64700 from 0x7f1211421780
Entering thread summarizer pause from 0x7f1211421780
Finished thread summarizer pause from 0x7f1211421780.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 24454]
[New LWP 24455]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f1210c0423a in __waitpid (pid=24457, stat_loc=0x7ffeb8dda794, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7f1211421780 (LWP 24453) "mono" 0x00007f1210c0423a in __waitpid (pid=24457, stat_loc=0x7ffeb8dda794, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f120efff700 (LWP 24454) "SGen worker" 0x00007f1210bff9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x556d1a0600e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7f120ca64700 (LWP 24455) "Finalizer" 0x00007f1210c026d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x556d1a051320) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7f120ca64700 (LWP 24455)):
#0  0x00007f1210c026d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x556d1a051320) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x556d1a051320, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f1210c027c8 in __new_sem_wait_slow (sem=0x556d1a051320, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000556d19c6df28 in ?? ()
#4  0x0000556d19c227fb in ?? ()
#5  0x00007f1210bf96db in start_thread (arg=0x7f120ca64700) at pthread_create.c:463
#6  0x00007f120ffe388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f120efff700 (LWP 24454)):
#0  0x00007f1210bff9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x556d1a0600e8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x556d1a060100, cond=0x556d1a0600c0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x556d1a0600c0, mutex=0x556d1a060100) at pthread_cond_wait.c:655
#3  0x0000556d19ccba1a in ?? ()
#4  0x00007f1210bf96db in start_thread (arg=0x7f120efff700) at pthread_create.c:463
#5  0x00007f120ffe388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f1211421780 (LWP 24453)):
#0  0x00007f1210c0423a in __waitpid (pid=24457, stat_loc=0x7ffeb8dda794, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000556d19a821c5 in ?? ()
#2  0x0000556d19a82251 in ?? ()
#3  0x0000556d19a2e0c1 in ?? ()
#4  0x0000556d19a814d2 in ?? ()
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#7  0x00007f120ff02801 in __GI_abort () at abort.c:79
#8  0x0000556d19cf0d17 in monoeg_assert_abort ()
#9  0x0000556d19cd6313 in ?? ()
#10 0x0000556d19cf0c98 in ?? ()
#11 0x0000556d19cf1193 in monoeg_assertion_message ()
#12 0x0000556d19bd16de in ?? ()
#13 0x0000556d19bd6a29 in ?? ()
#14 0x0000556d19b73f68 in ?? ()
#15 0x0000556d19bfb7d6 in ?? ()
#16 0x0000556d19ab8ace in ?? ()
#17 0x0000556d19a86a33 in ?? ()
#18 0x0000556d19a88d52 in ?? ()
#19 0x0000556d199f04a5 in ?? ()
#20 0x0000556d19a31756 in ?? ()
#21 0x0000556d19a322d3 in ?? ()
#22 0x0000000041163393 in ?? ()
#23 0x0000556d1b39c385 in ?? ()
#24 0x84c63dfd3f96be00 in ?? ()
#25 0x00007ffeb8ddcb20 in ?? ()
#26 0x00007ffeb8ddc958 in ?? ()
#27 0x0000556d1b3be700 in ?? ()
#28 0x00007f120f246da8 in ?? ()
#29 0x00007f120f246da8 in ?? ()
#30 0x0000000000000000 in ?? ()

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f120ff00e97):0x7f120ff00e87  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f120ff00e97  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
0x7f120ff00ea7  00 44 89 c0 75 1f 48 81 c4 18 01 00 00 c3 0f 1f  .D..u.H.........
0x7f120ff00eb7  00 48 8b 15 a9 bf 3a 00 f7 d8 41 b8 ff ff ff ff  .H....:...A.....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at BaslerCamera.Form1:.ctor <0x0004b>
	  at BaslerCamera.Form1:.ctor <0x0004f>
	  at BaslerCamera.Program:Main <0x0004b>
	  at System.Object:runtime_invoke_void <0x00086>
=================================================================
Aborted (core dumped)
`
